### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by pataquets**
I've also set up an example automated build at https://registry.hub.docker.com/u/pataquets/phpmongodb/ .
You can do a quick test by running this:

```
$ docker run --rm -it --net=host mongo # start a localhost-bound MongoDB node

$ docker run --rm -it --net=host -p 80:80 pataquets/phpmongodb # start a localhost-bound PHPMongoDB container
```

Navigate to http://localhost . Hit CTRL+C on each terminal to stop the respective container. 
PM will see MongoDB because its container shares localhost network stack. To implement Docker best practices, more customizable connection options should be added (e.g. environ vars).

### CODE REVIEW

**Comment by pataquets** [comment]
Bump

**Comment by phpmongodb** [comment]
I am going to change phpmongodb version are you want publish docker facility in first version

**Comment by pataquets** [comment]
Fetched upstream changes and image rebuid triggered. Everything is working as before.

**Comment by pataquets** [comment]
Note: remember to ```docker pull``` the newest image if old was already downloaded before.

**Comment by pataquets** [comment]
@phpmongodb : ping

**Comment by phpmongodb** [comment]
@pataquets 👍

**Comment by pataquets** [comment]
@phpmongodb : How about an (official) Automated Build from source on Docker Hub as a packaging method? https://docs.docker.com/docker-hub/builds/
Just a free Docker Hub account and a quick setup would do. Ping me if you need help.

**Comment by pataquets** [comment]
@phpmongodb : ping?

**Pull request merged**
